# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Sustainable Pace: Agile Coaching and Training"
email: info@sustainablepace.co.uk
description: "Sustainable Pace provides expert Agile coaching and training services to small and medium-sized businesses in South Wales."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sustainablepace.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: seize_the_dave
github_username:  seize-the-dave
social:
  links:
    - https://www.linkedin.com/company-beta/11064321/
google_analytics: "UA-222968-9"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
